# Generated by Django 3.2.7 on 2021-09-04 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bgallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(default='Photos', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image_description',
            field=models.TextField(default='Photos description'),
        ),
        migrations.AddField(
            model_name='photos',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bgallery.user'),
            preserve_default=False,
        ),
    ]
