# Generated by Django 3.2.7 on 2021-09-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgallery', '0002_auto_20210904_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='Photo', upload_to='photos/')),
                ('photo_name', models.CharField(max_length=40)),
                ('photo_description', models.TextField(default='Photo description')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgallery.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
